### ISSUE TITLE
"no protocol" error

### ISSUE THREAD

**Issue by ShadowSA** [khoih-prog/ESPAsync_WiFiManager#113]
### Describe the bug

When using the library manager in Arduino IDE, searching for ESPAsync_WiFiManager, then clicking install, throws error: "no protocol"

### Steps to Reproduce

Open Arduino IDE, select library manager, search ESPAsync_WiFiManager, click install on version 1.14.0

```

**Comment by khoih-prog** [comment]
You have to select `Install ESPAsync_WiFiManager only` to install the library.

The reason is that it depends on some other libraries which are **not** `published` or `well maintained` on Arduino IDE. You have to install them manually by downloading `zip`.

I'll possibly remove the dependency soon and make some notes about the issue.

Research or ask on Arduino Forum if you don't know how to install a library manually.

- ESP Async WebServer for both ESP32/ESP8266
- ESP AsyncTCP for both ESP8266
- AsyncTCP for both ESP32

![Selection_053](https://user-images.githubusercontent.com/57012152/190411993-30b6e7b0-8da1-4064-9a89-97f31722573d.png)

![Selection_052](https://user-images.githubusercontent.com/57012152/190412757-7e495abc-346d-4f02-a3fb-ab321eba6e18.png)

**Comment by khoih-prog** [comment]
Hi @ShadowSA 

The [**ESPAsync_WiFiManager** v1.14.1](https://github.com/khoih-prog/ESPAsync_WiFiManager/releases/tag/v1.14.1) has just been released to address the `dependency` issue.

Please test.

Regards,

---

### Releases v1.14.1

1. Remove dependency on ESP_AsyncWebServer, ESPAsyncTCP and AsyncTCP in `library.properties`. Check ["no protocol" error #113](https://github.com/khoih-prog/ESPAsync_WiFiManager/issues/113)"
2. Add notes about manual installation of above-mentioned libraries for `Arduino IDE`
