### ISSUE TITLE
Frequent run time error "Connecting MultiWifi..."

### ISSUE THREAD

**Issue by prakash52kar** [khoih-prog/ESPAsync_WiFiManager#129]
### Describe the bug

Just used the example code from Arduino IDE "Async_AutoConnect". The code successfully compiles and uploads in AIThinker ESP32CAM

### Expected behavior

It should give a captive portal and wait instead of giving this error repeatedly (may be restarting on its own)

### Actual behavior

As shown in the screenshot!

Please ensure to specify the following:

* Arduino IDE version 2.0.3 or Platform.io 
* ESP32 wrover Module
![Screenshot (73)](https://user-images.githubusercontent.com/57166940/210132532-6fe8a4da-e596-4b5c-bc61-c373341c046d.png)
* Just using example code from libraray in Arduino IDE
* It happens both in Arduino IDE as well as PlatformIO

![Screenshot (73)](https://user-images.githubusercontent.com/57166940/210132476-d00a93f2-48ef-4db7-9eed-884f3d556200.png)

**Comment by khoih-prog** [comment]
Don't use the simplest example [**Async_AutoConnect**](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_AutoConnect). The reset is intentional when you can't connect to WiFi (with SSID=0 and PW=0)

https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/a351dee184fd27d72b0c0232f5ac08af49003444/examples/Async_AutoConnect/Async_AutoConnect.ino#L415-L423

Use more complex [**Async_ConfigOnDoubleReset** example](https://github.com/khoih-prog/ESPAsync_WiFiManager/tree/master/examples/Async_ConfigOnDoubleReset), and use DRD to enter Config Portal to input correct SSID/PWD
