### ISSUE TITLE
Holy shit my friend! You are the wizard of oz

### ISSUE THREAD

**Issue by dm5xx** [khoih-prog/ESPAsync_WiFiManager#26]
Sorry for "Missusing" the issue tracker - but there is no other way to say thank you somehow! THANK YOU!!!! I want to spent you some beer - or some more, so please contact me via github for your paypal.

Mike.

**Comment by khoih-prog** [comment]
Thanks for your encouraging words and generous offer. I'm so sorry I won't get the offer as I've been working for fun only, without any financial interest.

I'm also so ashamed to be named `Wizard` as my libraries are based upon the works of many other people, who are the real `Wizards`. My working principle is just to try to stand on other people's shoulders and don't reinvent the wheels, and I'm sure yours is the same by successfully using the libraries to fulfill your projects.

I'll be happier if you can spend that offer on some `coffee` and have time to look at [**my other libraries**](https://www.arduinolibraries.info/authors/khoih-prog), see if you can apply to your future projects. You can also share your success usage of the library (without any company's secret) here so that other users can benefit from your experience.

I'll buy some beer, drink and remember your offer. Merry Christmas and Happy New Year.

Regards,

KH

PS: I've been in your nice city of Nurnberg, and the beautiful regions around it (Amberg, Rosenberg, Sulzbach-Rosenberg) and still remember the good beers there.
