### ISSUE TITLE
Connection problem

### ISSUE THREAD

**Issue by teodoroterra** [khoih-prog/ESPAsync_WiFiManager#36]
Hello friend, I would first like to congratulate you on all content shared and always updated with us.

I carried out tests using the Async_ConfigOnSwitch with version 1.4.2 modifying only the type of connection in the code and realized the following problems:
1- Using STA-mode DHCP the station ip is always 255.255.255.255
2 Using STA-mode StaticIP the first connection works fine as DHCP,  it also works fine after setting a static IP using the config in AP, but when rebooting it goes back to DHCP.  The station ip is changed to default Station IP just by opening and closing the AP.

A tip: I noticed that the original loop is stopped when the wifi is disconnected, to solve this I used multitasking where I put a task for connections and another task for reading sensors.

**Comment by khoih-prog** [comment]
First, thanks for your interests in the library.

I certainly need more information, not just looking at my crystal ball, and **waste my time to guess what's happening** from the scarce info you provided.

Have a look at [**How to create a Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), improve then post more terminal debug info to prove your point.

Then I'll definitely spend some more time to verify. I'm closing this now and re-open whenever the bug is proven.

I think from now on, I won't respond to any issue not following the minimum requirements as specified in [**How to submit a bug report**](https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/CONTRIBUTING.md#how-to-submit-a-bug-report)
