### ISSUE TITLE
Config portal in client mode

### ISSUE THREAD

**Issue by cultur98** [khoih-prog/ESPAsync_WiFiManager#41]
I have an application where i am happy to user the WiFiManager.
Since I added some config parameters I wondered if it is
possible to access the Portal also in Client mode, when I 
am connected to a hotspot.
These would easy the process of changing parameters here.

**Comment by khoih-prog** [comment]
> Since I added some config parameters I wondered if it is possible to access the Portal also in Client mode, when I am connected to a hotspot.

Sorry I don't understand what you mean here. Can you **clarify and post a detailed use-case**?

If it's convincing, I'll spend some time to look at and consider to add enhancement, or even a new library specially for that purpose.

**Comment by cultur98** [comment]
Sorry for the confusion. Maybe I should have described it in more detail. I added some parameters to the Configure Screen of your work. This is a nice and convenient interface for me.
The only thing is: I can only access the Configure Screen when the device is in AP Mode.
Is there a simple way to access the Configuration Screen when I am connected to a WiFi Hotspot and not in AP mode.

**Comment by khoih-prog** [comment]
This has been asked for and discussed many times before. But it's still not advisable to do so, even technically it's easy to do.

The issue is the boards still has to run (ESP)(Async)_WiFiManager, **consuming resources (memory, CPU, etc.) when not necessary.** The (ESP)(Async)_WiFiManager is only needed a short time to input / modify Credentials, then it's better to stop it when not using anymore.

So I won't spend time on this issue now.

Thanks for your suggestion anyway as we always need new ideas and suggestions like yours.

Please don't hesitate to post new convincing enhancement requests.
