### ISSUE TITLE
File Not Found error when accessing the config portal the second time

### ISSUE THREAD

**Issue by kanishgsivakumar** [khoih-prog/ESPAsync_WiFiManager#42]
HI ,
When i first connected to a network using the wifi portal it worked as it should when i wanted to change the network credentials for another network (when the first network is not available and esp32 is in AP mode) i get the following response in the static ip address
`File Not Found

URI: /
Method: GET
Arguments: 0`

**Comment by khoih-prog** [comment]
Have a look at [**How to create a Minimal, Reproducible Example**](https://stackoverflow.com/help/minimal-reproducible-example), improve then post more terminal debug info to prove your point.

Then I'll definitely spend some more time to verify. I'm closing this now and re-open whenever the bug is proven.

I won't respond to any issue not following the minimum requirements as specified in [**How to submit a bug report**](https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/CONTRIBUTING.md#how-to-submit-a-bug-report)
