### ISSUE TITLE
Click focus js bug on wifi page

### ISSUE THREAD

**Issue by idkq** [khoih-prog/ESPAsync_WiFiManager#71]
### Describe the bug

Weird behavior with focus. When I click on the name of the network link it populates SSID and SSID1 fields and move the focus to SSID1 password. When I start typing the password, the first char populates the first password box and then the focus moves to the second password box.

### Steps to Reproduce

On page wifi:

1. Click on the link of the network (in my case first link)
2. Type password.

You should see the first char in password box 1 and the rest on password box 2

![ezgif-7-7d15135b4ada](https://user-images.githubusercontent.com/76702881/140666049-ababa86f-0eee-4351-9733-c5d5e416e302.gif)

Also why does it populate 2 fields? Why do we have 4 boxes for user/pwd? I assume if user wants to add additional networks if one fails? How to remove SSID/pwd boxes?

**Comment by idkq** [comment]
Tested on safari and chrome

**Comment by khoih-prog** [comment]
Hi,

Thanks for your interests in the library.

It seems that your issue is strange and unique, system dependent as I can't duplicate here, using Chrome and Ubuntu Linux.


![Selection_076](https://user-images.githubusercontent.com/57012152/141029218-739d1fc0-6d4e-493e-b0e0-ec12510181dd.png)

---

> Also why does it populate 2 fields? Why do we have 4 boxes for user/pwd? I assume if user wants to add additional networks if one fails? How to remove SSID/pwd boxes?

I'm frustrated when the good feature, requested and useful to many people, is not fully understood and considered redundant. Anyway, nothing can fit all.

I suggest you to read [**Major Releases v1.1.1**](https://github.com/khoih-prog/ESPAsync_WiFiManager/blob/master/changelog.md#major-releases-v111) and use pre-v1.1.1 if requiring only 1 SSID. Or you can even ignore the 2nd SSID by leaving it blank.

There is no easy way to remove the MultiWiFi feature in releases v1.1.1+ and it's not recommended.
